{% set name = "rplibs" %}
{% set version = "6.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rplibs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 74e7f0092df1b4bcf67d28f5bd5a1d998d8eca7c8bac3ebdcd29d23151257266

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - networkx >=2.5
    - brs_utils
    - filetype
    - chemlite
    - rr_cache
    - cobra

test:
  source_files: 
    - tests/
  imports:
    - rplibs
  requires:
    - python {{ python_min }}
    - libsbml
    - pytest
  commands:
    - pytest tests/

about:
  home: https://github.com/brsynth/rplibs/tree/main
  summary: "Defines an enriched SBML structure with additional fields relative to RetroPath2 objects."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ramez17khaled
