context:
  name: unison
  version: "2.53.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/bcpierce00/unison/archive/v${{ version }}.tar.gz
  sha256: d0d30ea63e09fc8edf10bd8cbab238fffc8ed510d27741d06b5caa816abd58b6

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - ocaml
    - pkg-config
    - inotify

tests:
  - script:
      - unison -version
  - package_contents:
      bin:
        - unison

about:
  homepage: https://github.com/bcpierce00/unison
  summary: Unison file synchronizer
  license: GPL-3.0-only
  license_file: LICENSE
  repository: https://github.com/bcpierce00/unison

extra:
  recipe-maintainers:
    - niklasl
