context:
  version: "1.0.1"
  python_min: "3.10"

package:
  name: openapi-downgrade
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/openapi-downgrade/openapi_downgrade-${{ version }}.tar.gz
  sha256: "432c43a502610fb6b70ca64f67bcf60641d2d248de55fbd4ace8cfb3593ae9a8"

build:
  noarch: python
  script: python -m pip install . -vv
  python:
    entry_points:
      - openapi_downgrade = openapi_downgrade.cli:app
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - jsonschema >=4.19.0
    - typer
    - pyyaml
    - requests

tests:
  - python:
      imports:
      - openapi_downgrade
      - openapi_downgrade.converter
      python_version: ${{ python_min }}.*
      pip_check: true
  - script:
      - openapi_downgrade --help

about:
  homepage: https://github.com/RajeshRoy4426/openapi_downgrade_3_0
  summary: 'OpenAPI 3.1 to 3.0 converter GitHub'
  description: |
    Convert OpenAPI 3.1.x specifications to 3.0.x — with logic preservation,
    support for nullable, const, advanced schema handling, and conditionals via
    oneOf.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/RajeshRoy4426/openapi_downgrade_3_0

extra:
  recipe-maintainers:
    - I-Al-Istannen
