{% set name = "fastjet" %}
{% set version = "3.4.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastjet-{{ version }}.tar.gz
  sha256: 86dea05ce7a030db9fe14e5bf1c0bc46351b6e439f9b9ef6b14a55ceefcc7b7a
  patches:
    - 0001-Don-t-overwrite-external-CXXFLAGS-and-LDFLAGS.patch

build:
  number: 0
  skip: true  # [not linux]
  script:
    - echo "LOOK FOR ME"
    - command -v g++
    - g++ --version
    - ldconfig --print-cache | grep libgmp
    - {{ PYTHON }} -m pip install . -vv
  missing_dso_whitelist:
    - $RPATH/libfastjet.so.0
    - $RPATH/libfastjettools.so.0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - libtool
    - automake
    - autoconf
    - swig
    - gmp
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gxx
    - pip
    - pybind11
    - python
    - mpfr
    - cgal-cpp
    - gmp
    - patch
  run:
    - awkward >=2
    - numpy >=1.13.3
    - python
    - vector

test:
  imports:
    - fastjet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/fastjet
  summary: Official FastJet bindings to Python and Awkward Array.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - jpivarski
    - chrispap95
    - jmduarte
