{% set name = "fastjet" %}
{% set version = "3.4.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastjet-{{ version }}.tar.gz
  sha256: d7fd8f39e01873b1b1542c01feb57ceebcc361e45ec6bbb640893e6006c5bdc1
  patches:
    - 0001-Don-t-overwrite-external-CXXFLAGS-and-LDFLAGS.patch

build:
  number: 0
  skip: true  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv
  missing_dso_whitelist:
    - $RPATH/libfastjet.so.0
    - $RPATH/libfastjettools.so.0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - libtool
    - automake
    - autoconf
    - swig
  host:
    - pip
    - pybind11
    - python
    - cgal-cpp
    - gmp
  run:
    - awkward >=2
    - numpy >=1.13.3
    - python
    - vector

test:
  imports:
    - fastjet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/fastjet
  summary: Official FastJet bindings to Python and Awkward Array.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - jpivarski
    - chrispap95
    - jmduarte
