schema_version: 1

context:
  version: 0.15.1

package:
  name: flair-inference
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/flair-inference/flair_inference-${{ version }}.tar.gz
  sha256: 1d71cd4598673f4aa87842136feaa817d7c647a46ba429a9cbc66ea06ab5e1a4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - conllu >=4.0,<5.0.0
    - deprecated >=1.2.13
    - ftfy >=6.1.0
    - gdown >=4.4.0
    - huggingface_hub >=0.10.0
    - langdetect >=1.0.9
    - lxml >=4.8.0
    - more-itertools >=8.13.0
    - mpld3 >=0.3
    - pptree >=3.1
    - python-dateutil >=2.8.2
    - regex >=2022.1.18
    - scikit-learn >=1.0.2
    - segtok >=1.5.11
    - tabulate >=0.8.10
    - pytorch >=1.13.1
    - tqdm >=4.63.0
    - transformers >=4.45.0,<5.0.0
    - python-bioc <3.0.0,>=2.0.0

tests:
  - python:
      imports:
        - flair
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A very simple framework for state-of-the-art NLP
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mrubenw/flair-inference

extra:
  recipe-maintainers:
    - mrubenw
