{% set version = '0.2.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mgcviz
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mgcViz_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mgcViz/mgcViz_{{ version }}.tar.gz
  sha256: 82ec71ecd2453a35a757889d9b1ad95844517622fd138b2f7bde345f20b32973

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggally
    - r-kernsmooth
    - r-gamm4
    - r-ggplot2
    - r-gridextra
    - r-matrixstats
    - r-mgcv >=1.9
    - r-plyr
    - r-qgam >=1.2.3
    - r-viridis
  run:
    - r-base
    - r-ggally
    - r-kernsmooth
    - r-gamm4
    - r-ggplot2
    - r-gridextra
    - r-matrixstats
    - r-mgcv >=1.9
    - r-plyr
    - r-qgam >=1.2.3
    - r-viridis

test:
  commands:
    - $R -e "library('mgcViz')"           # [not win]
    - "\"%R%\" -e \"library('mgcViz')\""  # [win]

about:
  home: https://github.com/mfasiolo/mgcViz
  license: GPL-3.0-only
  summary: Extension of the 'mgcv' package, providing visual tools for Generalized Additive Models
    that exploit the additive structure of such models, scale to large data sets and
    can be used in conjunction with a wide range of response distributions. The focus
    is providing visual methods for better understanding the model output and for aiding
    model checking and development beyond simple exponential family regression. The
    graphical framework is based on the layering system provided by 'ggplot2'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - funnell

# Package: mgcViz
# Title: Visualisations for Generalized Additive Models
# Date: 2025-07-2
# Version: 0.2.1
# Authors@R: c(person("Matteo", "Fasiolo", email = "matteo.fasiolo@gmail.com", role = c("aut", "cre")), person("Raphael", "Nedellec", email = "raphael.nedellec@edf.fr", role = c("aut")), person("Yannig", "Goude", role = c("ctb")), person("Christian", "Capezza", role = c("ctb")), person("Simon", "N. Wood", role = c("ctb")))
# Description: Extension of the 'mgcv' package, providing visual tools for Generalized Additive Models that exploit the additive structure of such models, scale to large data sets and can be used in conjunction with a wide range of response distributions. The focus is providing visual methods for better understanding the model output and for aiding model checking and development beyond simple exponential family regression. The graphical framework is based on the layering system provided by 'ggplot2'.
# Depends: R (>= 4.0), mgcv (>= 1.9), qgam (>= 1.2.3), ggplot2
# Imports: gamm4, matrixStats, viridis, GGally, KernSmooth, gridExtra, plyr
# Suggests: shiny, miniUI, rgl, knitr, rmarkdown, testthat, MASS, webshot2
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# VignetteBuilder: knitr
# URL: https://github.com/mfasiolo/mgcViz
# BugReports: https://github.com/mfasiolo/mgcViz/issues
# NeedsCompilation: no
# Packaged: 2025-07-03 15:36:40 UTC; mf15002
# Author: Matteo Fasiolo [aut, cre], Raphael Nedellec [aut], Yannig Goude [ctb], Christian Capezza [ctb], Simon N. Wood [ctb]
# Maintainer: Matteo Fasiolo <matteo.fasiolo@gmail.com>
# Repository: CRAN
# Date/Publication: 2025-07-04 09:50:02 UTC
