{% set name = "pyasynchat" %}
{% set version = "1.0.5" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36665473ae730dac51e6d7dad70f8295962120c830ab692f0a31efba32687e24

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyasyncore >=1.0.5

test:
  imports:
    - asynchat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simonrob/pyasynchat
  summary: Make asynchat available for Python 3.12 onwards
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anderslindho
