context:
  version: "1.2.0"

package:
  name: openspec
  version: ${{ version }}

source:
  url: https://github.com/Fission-AI/OpenSpec/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 82ed0b4bd7f8179bf5e9cbc90792498184ed48898202d50527edd5c39545e16e

build:
  script:
    - if: unix
      then:
        - set -ex
        - pnpm install --ignore-scripts
        - pnpm build
        - npm pack --ignore-scripts
        - npm install --global ${SRC_DIR}/fission-ai-openspec-${{ version }}.tgz
        - pnpm-licenses generate-disclaimer --prod --output-file=third-party-licenses.txt
      else:
        - call pnpm install --ignore-scripts
        - if %ERRORLEVEL% neq 0 exit 1
        - call pnpm build
        - if %ERRORLEVEL% neq 0 exit 1
        - call npm pack --ignore-scripts
        - if %ERRORLEVEL% neq 0 exit 1
        - call npm install --global %SRC_DIR%/fission-ai-openspec-${{ version }}.tgz
        - if %ERRORLEVEL% neq 0 exit 1
        - call pnpm-licenses generate-disclaimer --prod --output-file=third-party-licenses.txt
        - if %ERRORLEVEL% neq 0 exit 1
  number: 0

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - openspec --help

about:
  homepage: https://openspec.dev
  summary: Spec-driven development (SDD) for AI coding assistants.
  description: |
    difit is a CLI tool that lets you view and review local git diffs with a GitHub-style viewer.
    In addition to clean visuals, comments can be copied as prompts for AI.
    The local code review tool for the AI era!
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  documentation: https://github.com/Fission-AI/OpenSpec
  repository: https://github.com/Fission-AI/OpenSpec

extra:
  recipe-maintainers:
    - pavelzw
