context:
  name: mip-sdk
  version: 4.0.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/HBK-MicroStrain/mip_sdk/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0ed3eb4429526c901c1c852201ad6e55453a6b112d7dd71781c3a708d5e0199c

build:
  number: 0
  script:
    - if: unix
      then:
        - echo ${CMAKE_ARGS}
        - cmake -S . -B build/
          ${CMAKE_ARGS}
          -GNinja
          -DBUILD_SHARED_LIBS=ON
          -DMICROSTRAIN_ENABLE_EXTRAS=ON
          -DMICROSTRAIN_BUILD_TESTS=ON
          -DDOCTEST_NO_INSTALL=ON
          -DMICROSTRAIN_BUILD_PACKAGE=OFF
          -DMICROSTRAIN_BUILD_EXAMPLES=OFF
          -DMICROSTRAIN_BUILD_DOCUMENTATION_QUIET=OFF
    - if: win
      then:
        - echo %CMAKE_ARGS%
        - cmake -S . -B build/
          %CMAKE_ARGS%
          -GNinja
          -DBUILD_SHARED_LIBS=ON
          -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin
          -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=lib
          -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=lib
          -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON
          -DMICROSTRAIN_ENABLE_EXTRAS=ON
          -DMICROSTRAIN_BUILD_TESTS=OFF
          -DDOCTEST_NO_INSTALL=ON
          -DMICROSTRAIN_BUILD_PACKAGE=OFF
          -DMICROSTRAIN_BUILD_EXAMPLES=OFF
          -DMICROSTRAIN_BUILD_DOCUMENTATION_QUIET=OFF
    - cmake --build build/ --config Release
    - cmake --install build/ --config Release
    - ctest --test-dir build/ --build-config Release --verbose --output-on-failure

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run:
  run_exports:
    - ${{ pin_subpackage('mip-sdk', upper_bound='x.x') }}

tests:
  - script:
      - cmake-package-check mip --targets
        mip_extras
        mip_metadata
      - cmake-package-check microstrain --targets
        microstrain_extras
        microstrain_recording_connection
        microstrain_serial
        microstrain_socket
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - cmake-package-check

about:
  homepage: https://github.com/HBK-MicroStrain/mip_sdk
  license: MIT
  license_file: LICENSE
  repository: https://github.com/HBK-MicroStrain/mip_sdk
  summary: MicroStrain Communications Library for embedded systems

extra:
  recipe-maintainers:
    - diegoferigo
