{% set version = "0.1.0" %}

package:
  name: xzarrguard
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xzarrguard/xzarrguard-{{ version }}.tar.gz
  sha256: dbbff155b731126ef500142b675ef426a7b4102b1856b7b81dd0d757979c6d49

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - xzarrguard = xzarrguard.cli:main
  number: 0

requirements:
  host:
    - python >=3.12
    - hatchling >=1.25.0
    - pip
  run:
    - python >=3.12
    - xarray >=2024.9.0
    - zarr >=3.0.0

test:
  imports:
    - xzarrguard
  commands:
    - pip check
      - xzarrguard --help
      - pytest -q -o addopts='' tests
  files:
    source:
      - tests/
  requires:
    - pip
    - python
    - pytest

about:
  home: https://github.com/j-haacker/xzarrguard
  repository: https://github.com/j-haacker/xzarrguard
  summary: Integrity checks and creation helpers for Zarr v3 stores
  doc_url: https://j-haacker.github.io/xzarrguard/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-haacker
