schema_version: 1

context:
  python_min: 3.12
  version: 1.1.5

package:
  name: adaptivetesting
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/adaptivetesting/adaptivetesting-${{ version }}.tar.gz
  sha256: b6fdce31d6e4f9784509e85b55872f952d999c603957faf0dfa4581ed83d6937

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.0.0
    - pandas >=2.2.0
    - scipy >=1.12.0
    - tqdm >=4.66.0
    - matplotlib-base >=3.9.0

tests:
  - python:
      imports:
        - adaptivetesting
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: adaptivetesting is a Python package that can be used to simulate and evaluate custom CAT scenarios as well as implement them in real-world testing scenarios from a single codebase
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/condecon/adaptivetesting
  documentation: https://github.com/condecon/adaptivetesting/tree/main/docs

extra:
  recipe-maintainers:
    - condecon