context:
  version: 1.1.8
  python_min: "3.9"

package:
  name: kgcpy
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/k/kgcpy/kgcpy-${{ version }}.tar.gz
  sha256: 928867b11c81a08cb9a6724558583b33e7b7e0acd941f3576a8a47b71bd9e4dd

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
  - python >={{ python_min }}
  - setuptools >=61.0
  - pip
  run:
  - python >={{ python_min }}
  - pillow
  - pandas

tests:
- python:
    imports:
    - kgcpy
    pip_check: true

about:
  summary: Aids in identifying the Koeppen-Geiger (KG) climatic zone for a given latitude and longitude of any location.
  description: "# kgcpy\nAids in identifying the Köppen-Geiger (KG) climatic zone for\na given lat and lon of any location. The resolution of KG map is at 100 sec arc or approximately 3.087 km at the equator, reported by Rubel et al. [2016]. \n\nF. Rubel, K. Brugger, K. Haslinger, and I. Auer, (2016) <doi:10.1127/metz/2016/0816>.\n\n# Features\n - lookupCZ(lat, lon): identify the Köppen-Geiger (KG) climatic zone for a given lat and lon\n - tranlateZipCode('zipcode'): find the lat and lon for a given 'zipcode'\n - nearbyCZ(lat,lon,size=1): get possible climate zones from the central pixel and the surrounding 8 pixels when size is set to 1, and compare to the central pixel, aiming to determine if the provided location is in proximity to a climate zone boundary.\n - roundCoordinates(lat, lon): get the inputed number to nearest ’fine’ (100s) resolution grid point.\n - irradianceQuantile(kg_zone): get irradiance quantiles for each Koppen Geiger Climate Zone\n \n # Documentation\nDocumentation can be found on [ReadTheDocs](https://kgcpy.readthedocs.io/en/latest/):\n\n#  Setup\n1. Install it at bash\n```bash\n$ pip install kgcpy\n```\n2.\tImport it in python\n```python\nfrom kgcpy import *\n``` \n#  Examples\n***Find Köppen-Geiger zone, nearby Köppen-Geiger zones for a given zipcode, and irradiance quantiles***\n```python\nzipcode = '02134'\nlat,lon = translateZipCode(zipcode)\nkg_zone = lookupCZ(lat, lon)\nprint('Koppen geiger zone is '+ kg_zone)\n\nsize = 10\nkg_zone_nearby = nearbyCZ(lat, lon, size)\nprint('Koppen geiger zone of central pixel is '+ kg_zone_nearby[0] + '\\n' \n      + 'Percentage of the Köppen-Geiger zones that match the central pixel, taking into account the neighboring pixels '+ \"{:.1%}\".format(kg_zone_nearby[1]) + '\\n' \n      + 'List of Köppen-Geiger zones from nearby pixels is', kg_zone_nearby[2][:])\n\nres_irrQuan = irradianceQuantile(kg_zone)\nprint('The 98%, 80%, 50%, and 30% irradiance quantile of '+ kg_zone +' respectively is' , res_irrQuan[0] , res_irrQuan[1] , res_irrQuan[2], 'kWh/m2')\n``` \n***Print output Köppen-Geiger zone, nearby Köppen-Geiger zones for a given zipcode, and irradiance quantiles***\n\n#  Versions\nAll notable changes to this project will be documented in this file.\n## [1.1.0] - 2023-08-12 - Package created\n## [1.1.1] - 2023-08-15 - Update documentation\n## [1.1.2] - 2023-08-15 - Update example codes\n## [1.1.4] - 2024-06-24 - Efficency improvements, GitHub release, testing\n## [1.1.5] - 2024-07-03 - Changed name to better conform to convention\n\n#  Description\nThe kgcpy package is a python version of “kgc: Köppen-Geiger Climatic Zones” R package on CRAN https://cran.r-project.org/web/packages/kgc/index.html, with addiontal functions.\n\nAids in identifying the Köppen-Geiger (KG) climatic zone for a given location. The Köppen-Geiger climate zones were first published in 1884, as a system to classify regions of the earth by their relative heat and humidity through the year, for the benefit of human health, plant and agriculture and other human activity [1]. This climate zone classification system, applicable to all of the earths surface, has continued to be developed by scientists up to the present day.\n\nOne of authors (Rubel) has published updated, higher accuracy KG climate zone definitions [2]. In this package we use these updated high-resolution (100 sec arc) maps as the data source [3]. We provide functions that return the KG climate zone for a given longitude and lattitude, or for a given United States zip code. In addition the nearbyCZ() function will check climate zones nearby to check if the given location is near a climate zone boundary. Digital data, as well as animated maps, showing the shift of the climate zones are provided on the following website <http://koeppen-geiger.vu-wien.ac.at>.\n\n[1] W. Köppen, (2011) <doi:10.1127/0941-2948/2011/105>.\n\n[2] F. Rubel and M. Kottek, (2010) <doi:10.1127/0941-2948/2010/0430>.\n\n[3] F. Rubel, K. Brugger, K. Haslinger, and I. Auer, (2016) <doi:10.1127/metz/2016/0816>.\n\n## Funding Acknowledgements:\n"
  repository: https://github.com/cwru-sdle/kgcpy
  documentation: https://kgcpy.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/cwru-sdle/kgcpy

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - julian-belina
