context:
  version: 2.0.2

package:
  name: unitree-sdk2
  version: ${{ version }}

source:
  url: https://github.com/unitreerobotics/unitree_sdk2/archive/refs/tags/${{ version }}.zip
  sha256: aa05c28463b9f3c9459efce19485a9777644b5671eb10908f9ae0de880e0b2cc
  patches:
    - add-sched-include.patch
    - fix-destructors-cpp20.patch

build:
  number: 0
  skip: not linux
  script:
    - cmake -S . -B build/
      -GNinja
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=$PREFIX
      -DBUILD_EXAMPLES=OFF
      -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=NEVER
    - cmake --build build/ --target install

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
  run:

tests:
  - script:
      - cmake-package-check unitree_sdk2
    requirements:
      run:
        - ${{ stdlib('c') }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - cmake-package-check
  - script:
      - echo "Checking stdlib compatibility of installed shared libraries..."
      - export c_stdlib_version=${{ c_stdlib_version }}
      - check-glibc lib/*.so* lib/*.a*
    requirements:
      run:
        - cf-nvidia-tools

about:
  homepage: https://support.unitree.com/home/zh/developer
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/unitreerobotics/unitree_sdk2
  summary: Unitree robot sdk version 2.

extra:
  recipe-maintainers:
    - diegoferigo
