{% set version = "1.0.0" %}

package:
  name: diffly
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffly/diffly-{{ version }}.tar.gz
  sha256: eee2092c5e6aa402822312230018cf70e386ac8ec3c581cebf7bd58f7cbd15f7

build:
  entry_points:
    - diffly = diffly.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.11
    - polars >=1.32,<2
    - rich

test:
  imports:
    - diffly
  commands:
    - pip check
    - diffly --help
  requires:
    - pip
    - python

about:
  home: https://pypi.org/project/diffly/
  summary: Utility package for comparing polars dataframes.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - EgeKaraismailogluQC
