{% set name = "uncalled-for" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5cdcff50ffdfc78060c5cea2b9d089c8349924d5af8a45bdeceebfecfa1407bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - uncalled_for

about:
  home: https://github.com/chrisguidry/uncalled-for
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Async dependency injection for Python functions
  description: |
    A small, focused dependency injection toolkit for async Python functions,
    extracted from the common bits of Docket and FastMCP.
  dev_url: https://github.com/chrisguidry/uncalled-for
  doc_url: https://github.com/chrisguidry/uncalled-for

extra:
  recipe-maintainers:
    - chrisguidry
    - zzstoatzz
