schema_version: 1

context:
  version: "1.10.0"

package:
  name: alembic-postgresql-enum
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/alembic-postgresql-enum/alembic_postgresql_enum-${{ version }}.tar.gz
  sha256: ea23481de3d6a00d68d369f92a46ff4fa27b2575e39c583145f1e23ea9c7511d

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - sqlalchemy >=1.4
    - alembic >=1.7

tests:
  - python:
      imports:
        - alembic_postgresql_enum
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/Pogchamp-company/alembic-postgresql-enum
  summary: Alembic autogenerate support for creation, alteration and deletion of enums
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ytausch
