{% set name = "nxs-analysis-tools" %}
{% set version = "0.1.14" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/d/nxs-analysis-tools/nxs_analysis_tools-{{ version }}.tar.gz
  sha256: f9a4b89c9769e0d1c585426d1881e1bebc72af3b09bf3760d7e1ef8cba1253ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - ipython
    - numpy
    - scipy
    - matplotlib
    - h5py
    - pandas
    - nexusformat
    - lmfit
    - astropy
    - pyfftw

test:
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/stevenjgomez/nxs_analysis_tools/
  summary: 'nxs-analysis-tools provides a suite of tools for performing 
    slices (2D), cuts (1D), and transformations (e.g., symmetrization, 
    interpolation, delta-PDF) on NeXus format (.nxs) scattering data.'
  description: |
    nxs-analysis-tools is a toolkit for managing and analyzing single crystal 
    scattering datasets that have already been processed and stored in the NeXus 
    file format (.nxs). Some notable functionalities are facile plotting of 
    arbitrary reciprocal space planes with the correct angle between axes, data 
    symmetrization, an all-in-one class for difference pair distribution function 
    analysis (delta-PDF), data rotations, linecuts, rebinning, and even 
    interactive / animated plots for an easier exploration of reciprocal space. 
    For data output from data reduction tools like NXRefine, this package also 
    provided a means to analyze an entire temperature series of scattering data 
    at once, allowing for easier analysis of temperature-dependent features in 
    the data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://nxs-analysis-tools.readthedocs.io/
  dev_url: https://github.com/stevenjgomez/nxs_analysis_tools

extra:
  recipe-maintainers:
    - stevenjgomez
    - Tieqiong
