{% set name = "xwmt" %}
{% set version = "0.1.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xwmt/xwmt-{{ version }}.tar.gz
  sha256: 81d58c8b376099a795eafed748458eb5340b6185c2a64dedece7bb437713ca2b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - gsw
    - numba
    - numpy
    - bottleneck
    - pandas
    - xarray
    - xhistogram
    - xgcm >=0.9.0
    - xbudget >=0.5.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - xwmt

about:
  home: https://github.com/NOAA-GFDL/xwmt
  summary: Water Mass Transformation Routines for xarray
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hdrake
