# Define variables in this section that you can use in other parts.
context:
  name: uraster
  version: "0.1.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/changliao1025/uraster/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9efd23b726c4aa13844f60562f47e6814371184ddc55f9f4633e4430a8d6db1e

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=${{ python_min }}
    - numpy
    - gdal >=3.0.0
    - pyearth >=0.2.2
    - pyearthviz3d >=0.1.1
    - psutil
    - pooch

tests:
  - python:
      imports:
        - uraster
        - uraster.classes
        - uraster.mesh
        - uraster.operation
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/changliao1025/uraster
  summary: 'Structured Raster to Unstructured Mesh'
  description: |
    URaster is a Python package to convert structured raster datasets into unstructured mesh structure,
    designed to bridge the gap between structured raster datasets and unstructured mesh-based hydrologic
    and land surface models. It leverages GDAL/OGR for robust data handling and provides interactive
    GeoVista API for 3D visualization on a sphere.
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://uraster.readthedocs.io/
  repository: https://github.com/changliao1025/uraster

extra:
  recipe-maintainers:
    - changliao1025
