context:
  version: "0.14.0"

package:
  name: wasm-pack
  version: ${{ version }}

source:
  url: https://github.com/drager/wasm-pack/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 60e866ce851219b18b7e16b2dbcd8323d5af0eac7d3a8a616bec3bd62fc051c4

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - wasm-pack --help
  - package_contents:
      bin:
        - wasm-pack

about:
  homepage: https://github.com/drager/wasm-pack
  summary: Your favorite Rust to Wasm workflow tool!
  description: |
    wasm-pack is a one-stop-shop for building and working with Rust-generated
    WebAssembly that you would like to interop with JavaScript, in the browser
    or with Node.js. wasm-pack helps you build Rust-generated WebAssembly
    packages that you could publish to the npm registry, or otherwise use
    alongside any JavaScript packages in workflows that you already use.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  documentation: https://drager.github.io/wasm-pack/
  repository: https://github.com/drager/wasm-pack

extra:
  recipe-maintainers:
    - Hofer-Julian
