context:
  version: "0.17.0"

package:
  name: mdbook-mermaid
  version: ${{ version }}

source:
  url: https://github.com/badboy/mdbook-mermaid/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ed155c57d4356b90c26806a8699a1287712831e45c0cc6e5eb7ed4cc7fd4ada7

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then: |
          cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
          cargo auditable install --locked --no-track --path . --root ${PREFIX}
        else: |
          cargo-bundle-licenses --format yaml --output %SRC_DIR%\THIRDPARTY.yml
          cargo auditable install --locked --no-track --path . --root %LIBRARY_PREFIX%

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - mdbook-mermaid --version

about:
  homepage: https://github.com/badboy/mdbook-mermaid
  license: MPL-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: "A preprocessor for mdbook to add mermaid support"
  summary: "A preprocessor for mdbook to add mermaid support"

extra:
  recipe-maintainers:
    - VasanthakumarV
