context:
  version: "0.2.1"

package:
  name: nviwatch
  version: ${{ version }}

source:
  url: https://github.com/msminhas93/nviwatch/archive/refs/tags/v${{ version }}.tar.gz
  sha256: de36130bbbb27fb5d656c8758e4cb5049434d82e8ee48c85859ebb26c280c1df

build:
  number: 0
  skip:
    - osx
    - win
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo auditable install --locked --root ${{ PREFIX }} --path .

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-auditable
    - cargo-bundle-licenses

tests:
  - script:
      - nviwatch --version
      - nviwatch --help

about:
  homepage: https://github.com/msminhas93/nviwatch
  repository: https://github.com/msminhas93/nviwatch
  documentation: https://github.com/msminhas93/nviwatch/blob/v${{ version }}/README.md
  license: MIT
  license_file:
   - LICENSE
   - THIRDPARTY.yml
  summary: A blazingly fast rust based TUI for managing and monitoring NVIDIA GPU processes
  description: |
    NviWatch is an interactive terminal user interface (TUI) application for monitoring NVIDIA GPU devices and processes.
    Built with Rust, it provides real-time insights into GPU performance metrics, including temperature, utilization, memory usage, and power consumption.

extra:
  recipe-maintainers:
    - eunos-1128
