{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggokabeito
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggokabeito_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggokabeito/ggokabeito_{{ version }}.tar.gz
  sha256: 97b59ada139683443d534f5f643927fed0af1105c981db22d75ed07f10fe8b1e

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
  run:
    - r-base
    - r-ggplot2

test:
  commands:
    - $R -e "library('ggokabeito')"           # [not win]
    - "\"%R%\" -e \"library('ggokabeito')\""  # [win]

about:
  home: https://github.com/malcolmbarrett/ggokabeito, https://malcolmbarrett.github.io/ggokabeito/
  license: MIT
  summary: Discrete scales for the colorblind-friendly 'Okabe-Ito' palette, including 'color',
    'fill', and 'edge_colour'. 'ggokabeito' provides 'ggplot2' and 'ggraph' scales to
    easily use the 'Okabe-Ito' palette in your data visualizations.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - funnell

# Package: ggokabeito
# Title: 'Okabe-Ito' Scales for 'ggplot2' and 'ggraph'
# Version: 0.1.0
# Authors@R: person("Malcolm", "Barrett", , "malcolmbarrett@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-0299-5825"))
# Description: Discrete scales for the colorblind-friendly 'Okabe-Ito' palette, including 'color', 'fill', and 'edge_colour'. 'ggokabeito' provides 'ggplot2' and 'ggraph' scales to easily use the 'Okabe-Ito' palette in your data visualizations.
# License: MIT + file LICENSE
# URL: https://github.com/malcolmbarrett/ggokabeito, https://malcolmbarrett.github.io/ggokabeito/
# BugReports: https://github.com/malcolmbarrett/ggokabeito/issues
# Depends: R (>= 4.0.0)
# Imports: ggplot2, grDevices
# Suggests: covr, ggraph, igraph, spelling, testthat (>= 3.0.0), vdiffr
# Config/testthat/edition: 3
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.1.2
# NeedsCompilation: no
# Packaged: 2021-10-15 19:30:07 UTC; malcolmbarrett
# Author: Malcolm Barrett [aut, cre] (<https://orcid.org/0000-0003-0299-5825>)
# Maintainer: Malcolm Barrett <malcolmbarrett@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-10-18 14:40:04 UTC
