schema_version: 1

context:
  name: fast-simplification
  version: 0.1.13

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace("-", "_")|lower }}-${{ version }}.tar.gz
  sha256: 5e95c966ad4ddf04b0a49013c92e5a06a3b888c6e02bb3c7ab3817fc8ba0f03f

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - cython >=3.0.0
    - numpy
    - pip
    - python
    - setuptools >=45.0
    - wheel >=0.37.0
  run:
    - python

tests:
  - python:
      imports:
        - fast_simplification
      pip_check: true
  - script:
      - pytest ./tests/
    files:
      source:
        - tests/
    requirements:
      run:
        - pyvista
        - pytest

about:
  homepage: https://pyvista.github.io/fast-simplification
  license: MIT
  license_file: LICENSE
  repository: https://github.com/pyvista/fast-simplification
  summary: Fast Quadratic Mesh Simplification

extra:
  recipe-maintainers:
    - diegoferigo
    - akaszynski
