context:
  version: "3.6.0"
  python_min: "3.9"

package:
  name: rapidocr
  version: ${{ version }}

source:
  url: https://github.com/RapidAI/RapidOCR/archive/v${{ version }}.tar.gz
  sha256: 8b061f87053e37e1943c0f372fffa2a6a52f064018ee69cceaeb32e8143ff782

build:
  noarch: python
  script: build.sh
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pyclipper >=1.2.0
    - py-opencv >=4.5.1.48
    - numpy >=1.19.5,<3.0.0
    - six >=1.15.0
    - shapely >=1.7.1,!=2.0.4
    - pyyaml
    - pillow
    - tqdm
    - omegaconf
    - requests
    - colorlog

tests:
  - python:
      imports:
        - rapidocr
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/RapidAI/RapidOCR
  summary: Awesome OCR Library
  description: |
    A cross platform OCR Library based on OnnxRuntime/OpenVINO/PaddlePaddle.
    It supports text detection and recognition.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://rapidai.github.io/RapidOCRDocs
  repository: https://github.com/RapidAI/RapidOCR

extra:
  recipe-maintainers:
    - kklein
