schema_version: 1

context:
  version: "0.6"

package:
  name: pyseas
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyseas/pyseas-${{ version }}.tar.gz
  sha256: a011356a532accac0acb0e69480fcbd896990ac20a2dc05d72eaa0876bea08b1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - requests >=2.0

tests:
  - python:
      imports:
        - pyseas
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A Python wrapper for seas-nve API
  homepage: https://bitbucket.org/ooicgsn/pyseas
  license: MIT
  # https://bitbucket.org/ooicgsn/pyseas/raw/eea6201da6a97a0aacf66c95efcfda21f1b595ec/LICENSE.txt
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
