{% set version = "1.0.0" %}
{% set posix = "m2-" if win else "" %}

package:
  name: r-rmacrostrat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rmacrostrat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rmacrostrat/rmacrostrat_{{ version }}.tar.gz
  sha256: c0ec17230a4d568463a8aeea2e565815d857f775675104ef42cdaea9d55709a7

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip  # [win]
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
  host:
    - r-base
    - r-curl
    - r-geojsonsf
    - r-httr
    - r-jsonlite
    - r-sf
  run:
    - r-base
    - r-curl
    - r-geojsonsf
    - r-httr
    - r-jsonlite
    - r-sf

test:
  requires:
    - r-testthat
  source_files:
    - tests/
  commands:
    - $R -e "library('rmacrostrat')"  # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"  # [not win]
    - "\"%R%\" -e \"library('rmacrostrat')\""  # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://rmacrostrat.palaeoverse.org/
  license: GPL-3.0-or-later
  summary: Fetch Geologic Data from the 'Macrostrat' Platform
  description: |
    Work with the 'Macrostrat' (<https://macrostrat.org/>) Web Service
    (v.2, <https://macrostrat.org/api/v2>) to fetch geological data relevant
    to the spatial and temporal distribution of sedimentary, igneous, and
    metamorphic rocks as well as data extracted from them.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
  dev_url: https://github.com/palaeoverse/rmacrostrat
  doc_url: https://rmacrostrat.palaeoverse.org/

extra:
  recipe-maintainers:
    - conda-forge/r
    - willgearty
