{% set version = "0.1.7" %}
{% set python_min = "3.10" %}

package:
  name: cdsswarm
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cdsswarm/cdsswarm-{{ version }}.tar.gz
  sha256: 10ee4f44c71240021f036f77b6e2fab76ae75fecbd11e1170d1a8c40d0f15516

build:
  noarch: python
  entry_points:
    - cdsswarm = cdsswarm.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - cdsapi >=0.7
    - requests
    - tqdm
    - textual >=0.87
    - tomli >=1.1.0

test:
  imports:
    - cdsswarm
  commands:
    - pip check
    - cdsswarm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bgiebl/cdsswarm
  summary: Concurrent CDS API downloader with TUI and script mode
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgiebl
