schema_version: 1

context:
  python_min: 3.11
  version: 1.0.1

package:
  name: livvext
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/livvext/livvext-${{ version }}.tar.gz
  sha256: ec90302d09a438e806282e29f396514ed82fda091103c57165617b16cd84ae3f

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  python:
    entry_points:
      - lex-cfg = livvext.generate_cfg:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.2.6
    - scipy >=1.17.0
    - xarray >=2025.6.1
    - dask-core >=2026.1.2
    - seaborn >=0.13.2
    - cftime >=1.6.5
    - nc-time-axis >=1.4.1
    - scikit-learn >=1.7.2
    - ruamel.yaml >=0.19.1
    - jinja2 >=3.1.6
    - matplotlib-base >=3.10.8
    - mache >=2.1.0
    - nco >=5.3.6
    - netcdf4 >=1.7.4
    - pandas >=2.2.3
    - cartopy >=0.25.0
    - pybtex >=0.25.1
    - f90nml >=1.5
    - loguru >=0.7.3
    - livvkit >=3.3.0

tests:
  - python:
      imports:
        - livvext
      pip_check: false
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - lex-cfg --help

about:
  summary: Extensions for the land ice verification and validation toolkit (Livvkit EXtensions)
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/LIVVkit/livvext

extra:
  recipe-maintainers:
    - mkstratos
