{% set version = "0.2.0" %}

package:
  name: tomlkit-extras
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tomlkit-extras/tomlkit_extras-{{ version }}.tar.gz
  sha256: 311b5da3d63dbbe6ae45c550573ea076dafddd2158bc095d48f3dab2fe5903fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - tomlkit >=0.13.0
    - pyrsistent >=0.20.0
    - charset-normalizer >=3.3.2
    - pathvalidate >=3.2.0
    - typing_extensions >=4.6.0

test:
  imports:
    - tomlkit_extras
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/galactixx/tomlkit-extras
  summary: A Python package that extends the functionality of tomlkit, allowing for advanced manipulation, validation, and introspection of TOML files, including handling comments and nested structures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - frankier
