context:
  version: "1.33"

package:
  name: aws-lambda-runtime-interface-emulator
  version: ${{ version }}

source:
  url: https://github.com/aws/aws-lambda-runtime-interface-emulator/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7ff395aca2293811a8bb2eb6d5e84c1a9293f8bef7d1e4b87a01e316a1ef39d9
  target_directory: src

build:
  number: 0
  script:
    - cd src/cmd/aws-lambda-rie
    - go-licenses save . --save_path ../../../library_licenses
    - if: unix
      then: go build -v -o $PREFIX/bin/aws-lambda-rie -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\aws-lambda-rie.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  # The script doesn't have options, it always starts a server.
  # - script: aws-lambda-rie -help
  - package_contents:
      bin:
        - aws-lambda-rie
      strict: true

about:
  homepage: https://github.com/aws/aws-lambda-runtime-interface-emulator
  summary: AWS Lambda Runtime Interface Emulator
  description: |
    The Lambda Runtime Interface Emulator is a proxy for Lambda’s Runtime and Extensions APIs, which allows customers to locally test their Lambda function packaged as a container image.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  documentation: https://pkg.go.dev/github.com/aws/aws-lambda-runtime-interface-emulator
  repository: https://github.com/aws/aws-lambda-runtime-interface-emulator

extra:
  recipe-maintainers:
    - xhochy
